### ISSUE TITLE
Excessive object rebuilding when 'Subscribed' children of ResizablePanel

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/object_database#68]
if we have a subscribed sequence as a child in a ResizablePanel, and one of the sequence items rebuilds, it causes the ResizablePanel itself to rebuild, which triggers a walk down the dom tree in javascript, which disrupts UX state such as ace editor state, plotly state, dropdown state, etc.

We need to be figuring out exactly which children actually changed and restricting our dom update to just those individual components.

**Comment by darth-cheney** [comment]
I think I get what's going on. This has to do with how we are collapsing Subscribeds and SubscribedSequences into their parents (so long as they also are not Subs). This strategy works in most cases. But with ResizablePanel we essentially have a Cell type that can "split" a deeply nested tree structure of Cells. So if a SubscribedSequence is, say, on the right panel and it changes somehow, the left panel is also updated again. In large structures this can be annoying.
  
A quick and possibly easy fix for this is to use a strategy that we employ on Dropdowns and Plot, which is to make the content area -- or in this case areas -- their own Cell type, and to have ResizablePanel automatically compose itself of these child types. Then any direct Subscribed/SubSequence children of each content area will be the Cell that they "collapse into".
  
What do you think?

**Comment by braxtonmckee** [comment]
I think that's an option, but I'd like to think about whether we can more
generally figure out how to only update the children that change. For
instance, if you have a subscribedsequence and one child gets removed, we
should be able to figure out that all we need to do (at the root
subscribedsequence) is remove that child without walking deeply into the
individual dom trees.  I'm not sure if that will be compatible with
maquette, but I see this issue with ResizablePanel as a specific symptom of
a much worse problem that we now have.

A good example of the deeper issue is that if I have a text ticker in a
panel next to a dropdown menu, and the text ticker is updating frequently,
then I can't interact with the dropdown menu at all because whenever I open
the dropdown menu, the next update to the text ticker causes it to rebuild
itself and the 'openness' state is lost. We really need to prevent that
from happening somehow.

**Comment by darth-cheney** [comment]
I see what you're saying and I definitely agree.
  
Let me think about this for a bit and screw around with a couple of ideas

**Comment by braxtonmckee** [comment]
i was thinking about it the other day and it occurred to me that we do know
the tree of changed children on the server, so we could surface a
representation of that in the protocol we send over.

**Comment by darth-cheney** [comment]
The problem (as it's always been) is determining where to insert that tree into the DOM. We removed Subscribed type cells ability to make their own elements because it was mucking up styling and layout. But the side effect is that the parent to a Subscribed is responsible for "knowing" where the content of that Subscribed should be inserted, and therefore that parent requires the update message.
  
When we first started, Subscribed types were just divs and anything they contained/updated went inside the div. I'm thinking we can try something related, but different: have Subscribeds inserted into the DOM as a div that has its display set to None, but rather than inserting the subtree inside of it, we insert the tree *after* that element. This gets past the styling/formatting issues, but allows a Subscribed on its own to know where to insert itself when its contents get updated.

**Comment by braxtonmckee** [comment]
That seems like a reasonable idea. To figure out what to update, you'd walk
between the subscribed-placeholder div and the next thing in that parent
that's also a subscribed-placeholder div and you'd know what to pull out.
Can we assume that there is exactly one div there since we're flattening
the tree?

**Comment by darth-cheney** [comment]
> you'd walk between the subscribed-placeholder div and the next thing in that parent
that's also a subscribed-placeholder div and you'd know what to pull out.
  
For once the DOM helps us here, though I had it backwards. Both the DOM and Maquette APIs allow us to quickly and easily insert an element *before* another element in their mutual parent. Because of this, we don't need to walk anything. Imagine the following case, a Subscribed wraps a Text that for whatever reason changes to a button, all inside of a panel. We would have a DOM that looks something like this at first (simplified):
```html
<div id="1" class="cell cell-panel" data-cell-id="1" data-cell-type="Panel">
    <div id="3" class="cell text" data-cell-id="3" data-cell-type="Text" data-subscribed-to="2">
        Hello!
    </div>
    <div id="2" data-cell-id="2" class="cell subscribed" data-cell-type="Subscribed"></div>
</div>
```
After the update it would look like this:
```html
<div id="1" class="cell cell-panel" data-cell-id="1" data-cell-type="Panel">
    <div id="4" class="cell button" data-cell-id="4" data-cell-type="Button" data-subscribed-to="2">
        Click Me
    </div>
    <div id="2" data-cell-id="2" class="cell subscribed" data-cell-type="Subscribed"></div>
</div>
```
As you can see, each time the contents of the Subscribed will be inserted before the actual Subscribed div (rather than inside of it). A Subscribed component can keep track of where it is, but also where any of its current contents are because of the `data-subscribed-to` attribute set on the content. The reverse is also true: any incoming Component that is the content of a given Subscribed can just look it up by id and know which element to insert before.

Finding the Subscribed element is as easy as `document.getElementById("2")`. Finding the contents for that element is as easy as `document.querySelector('[data-subscribed-to="2"]')`.
  
What I am not 100% sure of at this point is if having the Susbcribed divs set to `display: none` will actually prevent styling from getting screwed up. Best scenario is that there are only a few edge cases that require minor CSS adjustment.
  
I am definitely down to try this out though. It will require a bit of work -- we removed the `Subscribed` component entirely a couple of months back and decided to handle all of the complexity on the Cells side. We would need to undo parts of that and re-create the new Subscribed component.

**Comment by darth-cheney** [comment]
@braxtonmckee I've started with the simplest problem first, which was just to re-implement Subscribed components and allow the resulting elements to have children like normal (ie, none of this appendBefore/appendAfter stuff). I had assumed -- based on previous experience -- that this would much up our styling and perhaps some of the layouts. But after running tests and going through some of the examples, it looks like things are just working.
  
I am, of course, suspicious. So it would be good if you could test off the head of my working branch with some of the more deeply-nested / complex structures you use in the live environment when you have the change. Otherwise, we might not need to use the proposed strategy at all

**Comment by darth-cheney** [comment]
Handled in #86
